<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<NoWarn>$(NoWarn);ChangeMagicNumberToID</NoWarn>
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		<Reference Include="Terraria" HintPath="C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll" />
		<Reference Include="Redemption" HintPath="lib/Redemption.dll" />
		<Reference Include="Chickensubclass" HintPath="lib/Redemption.dll" />
	</ItemGroup>

</Project>